UdeCDocsMVC/Models/Faculty.cs
using System;
using System.Collections.Generic;

namespace UdeCDocsMVC.Models
{
    public partial class Faculty
    {
        public Faculty()
        {
            Fields = new HashSet<Field>();
            Users = new HashSet<User>();
        }

        public int Idfaculty { get; set; }
        public string Faculty1 { get; set; } = null!;
        public string? Description { get; set; } = null!;


        public virtual ICollection<Field> Fields { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}

UdeCDocsMVC/Controllers/DocumentsAPIController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using UdeCDocsMVC.Models.API;
using UdeCDocsMVC.Models;

namespace UdeCDocsMVC.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class DocumentsAPIController : ControllerBase
    {
        private readonly UdecDocsContext _context;

        public DocumentsAPIController(UdecDocsContext context)
        {
            _context = context;
        }
        //GET documento json
        // GET: api/DocumentsAPI/5
        [HttpGet("{id}")]
        public async Task<ActionResult<DocumentAPI>> GetDocument(int id)
        {
            var document = await _context.Documents.FindAsync(id);

            if (document == null)
            {
                return NotFound();
            }
            DocumentAPI documentAPI = new DocumentAPI
            {
                Name = document.Name,
                Abstract = document.Abstract,
                Keywords = document.Keywords,
                PublicationDate = document.PublicationDate,
                Authors = document.Authors,
                Direction = "http://udecdocs.somee.com/Uploads/" + document.Direction
            };

            List<Comment> comments = await _context.Comments.Where(c => c.Iddocument == id).ToListAsync();
            List<CommentAPI> commentAPIs = new List<CommentAPI>();
            foreach (Comment item in comments)
            {
                CommentAPI commentAPIaux = new CommentAPI
                {
                    Body = item.Body,
                    Date = item.Date,
                    UserW = item.UserW
                };
                commentAPIs.Add(commentAPIaux);
            }
            documentAPI.Comments = commentAPIs;
            List<Vote> upvotes = await _context.Votes.Where(c => c.Iddocument == id && c.IdtypeVote == 1).ToListAsync();
            List<Vote> downvotes = await _context.Votes.Where(c => c.Iddocument == id && c.IdtypeVote == 2).ToListAsync();
            documentAPI.Upvotes = upvotes.Count();
            documentAPI.Downvotes = downvotes.Count();
            return documentAPI;
        }
    }
}

UdeCDocsMVC/Controllers/DocumentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Xml.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.VisualBasic;
using NuGet.Packaging.Signing;
using UdeCDocsMVC.Models;
using UdeCDocsMVC.Models.SysModels;

namespace UdeCDocsMVC.Controllers
{

    public class DocumentsController : Controller
    {
        private readonly UdecDocsContext _context;
        private readonly IWebHostEnvironment _environment;

        public DocumentsController(UdecDocsContext context, IWebHostEnvironment environment)
        {
            _context = context;
            _environment = environment;
        }
        //Get document details
        // GET: Documents/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Documents == null)
            {
                return NotFound();
            }

            var document = await _context.Documents
                .Include(d => d.IdfieldNavigation)
                .FirstOrDefaultAsync(m => m.Iddocument == id);
            if (document == null)
            {
                return NotFound();
            }
            List<Vote> upvotes = await _context.Votes.Where(v => v.Iddocument == id && v.IdtypeVote == 1).ToListAsync();
            List<Vote> downvotes = await _context.Votes.Where(v => v.Iddocument == id && v.IdtypeVote == 2).ToListAsync();
            List<Comment> comments = await _context.Comments.Where(c => c.Iddocument == id).ToListAsync();
            document.Comments = comments;
            ViewData["upvotes"] = upvotes.Count;
            ViewData["downvotes"] = downvotes.Count;
            TempData["Iddocument"] = id;
            return View(document);
        }

        //Return view create document
        [Authorize(Policy = "RequireUdeCUserRole")]
        public IActionResult Create()
        {
            User user = _context.Users.Find(Int32.Parse(User.FindFirst("Iduser").Value));
            ViewData["Idfield"] = new SelectList(_context.Fields.Where(f => f.Idfaculty == user.Idfaculty), "Idfield", "Field1");
            return View();
        }

        //Upload document method=post
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "RequireUdeCUserRole")]
        public async Task<IActionResult> Create([Bind("Name,Abstract,Keywords,Authors,Direction,Idfield")] CDocument document)
        {
            using (_context)
            {
                if (document != null)
                {

                    string documentName = document.Direction.FileName;
                    var guid = Guid.NewGuid();
                    string documentNameDB = documentName + guid + ".pdf";
                    var fileName = System.IO.Path.Combine(_environment.ContentRootPath, "\\wwwroot\\Uploads", documentName + guid + ".pdf");
                    await document.Direction.CopyToAsync(new System.IO.FileStream(fileName, System.IO.FileMode.Create));
                    int Iduser = Int32.Parse(User.FindFirst("Iduser").Value);
                    DateTime date = DateTime.Now;
                    Document document1 = new Document
                    {
                        Name = document.Name,
                        Abstract = document.Abstract,
                        Keywords = document.Keywords,
                        PublicationDate = date,
                        Authors = document.Authors,
                        Direction = documentNameDB,
                        Idfield = document.Idfield,
                        Iduser = Iduser
                    };
                    _context.Documents.Add(document1);
                    await _context.SaveChangesAsync();
                    return RedirectToAction("Index", "Home");
                }
                User user = _context.Users.Find(Int32.Parse(User.FindFirst("Iduser").Value));
                ViewData["Idfield"] = new SelectList(_context.Fields.Where(f => f.Idfaculty == user.Idfaculty), "Idfield", "Field1", document.Idfield);
                return View(document);
            }

        }

        //Edit document
        // GET: Documents/Edit/5
        [Authorize(Policy = "RequireUdeCUserRole")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Documents == null)
            {
                return NotFound();
            }

            var document = await _context.Documents.FindAsync(id);
            if (document == null)
            {
                return NotFound();
            }
            ViewData["Idfield"] = new SelectList(_context.Fields, "Idfield", "Field1", document.Idfield);
            return View(document);
        }

        //Edit document
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "RequireUdeCUserRole")]
        public async Task<IActionResult> Edit(string Name, string Abstract, string Keywords, string Authors, int id)
        {
            if (!_context.Documents.Any(e => e.Iddocument == id))
            {
                return NotFound();
            }

            int Iduser = Int32.Parse(User.FindFirst("Iduser").Value);

            var document = await _context.Documents.FindAsync(id);

            if (Name != null || Abstract != null || Keywords != null || Authors != null)
            {
                if (document.Iduser == Iduser)
                {
                    document.Name = Name;
                    document.Abstract = Abstract;
                    document.Keywords = Keywords;
                    document.Authors = Authors;
                    _context.Update(document);
                    await _context.SaveChangesAsync();

                    return RedirectToAction("Details", "Users", new { id = Iduser });
                }
            }
            ViewData["Idfield"] = new SelectList(_context.Fields, "Idfield", "Field1", document.Idfield);
            return View(document);
        }

        //Delete document
        // GET: Documents/Delete/5
        [Authorize(Policy = "RequireUdeCUserRole")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Documents == null)
            {
                return NotFound();
            }

            var document = await _context.Documents
                .Include(d => d.IdfieldNavigation)
                .FirstOrDefaultAsync(m => m.Iddocument == id);
            if (document == null)
            {
                return NotFound();
            }

            return View(document);
        }

        //Delete document
        // POST: Documents/Delete/5
        [Authorize(Policy = "RequireUdeCUserRole")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Documents == null)
            {
                return Problem("Entity set 'UdeCDocsContext.Documents'  is null.");
            }
            var document = await _context.Documents.FindAsync(id);

            int Iduser = Int32.Parse(User.FindFirst("Iduser").Value);

            if (document != null)
            {
                if(document.Iduser == Iduser) 
                {
                    var listComments = await _context.Comments.Where(c => c.Iddocument == id).ToListAsync();
                    var listVotes = await _context.Votes.Where(v => v.Iddocument == id).ToListAsync();
                    if (listComments != null)
                    {
                        foreach (Comment c in listComments)
                        {
                            _context.Comments.Remove(c);
                        }
                    }
                    if (listVotes != null)
                    {
                        foreach (Vote v in listVotes)
                        {
                            _context.Votes.Remove(v);
                        }
                    }

                    var fileName = System.IO.Path.Combine(_environment.ContentRootPath, "wwwroot\\Uploads", document.Direction);
                    try
                    {
                        FileInfo file = new FileInfo(fileName);
                        file.Delete();
                    }
                    catch (Exception e)
                    {
                        return RedirectToAction("Index", "Home");
                    }

                    _context.Documents.Remove(document);

                    await _context.SaveChangesAsync();
                    return RedirectToAction("Details", "Users", new { id = Iduser });
                }
                
            }

            return RedirectToAction("Index", "Home");
        }

        //Create comment for document
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "RequireRegistered")]
        public async Task<IActionResult> CreateComment(string body)
        {
            int Iddocument = Int32.Parse(TempData["Iddocument"].ToString());
            if (body != null)
            {
                int Iduser = Int32.Parse(User.FindFirst("Iduser").Value);
                var user = await _context.Users.Where(u => u.Iduser == Iduser).SingleAsync();
                DateTime date = DateTime.Now;
                Comment comment = new Comment
                {
                    Body = body,
                    Date = date,
                    Iddocument = Int32.Parse(TempData["Iddocument"].ToString()),
                    Iduser = Iduser,
                    UserW = user.Name
                };
                _context.Comments.Add(comment);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Details), new { id = Iddocument });
            }

UdeCDocsMVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using System.Runtime.ConstrainedExecution;
using UdeCDocsMVC.Models;
using UdeCDocsMVC.Models.SysModels;

namespace UdeCDocsMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly UdecDocsContext _context;

        public HomeController(ILogger<HomeController> logger, UdecDocsContext context, IHttpContextAccessor httpContextAccessor)
        {
            _context = context;
            _logger = logger;
        }

        public async Task<IActionResult> Index()
        {
            var documents = await _context.Documents.ToListAsync();
            foreach (var document in documents) 
            {
                document.Votes = await _context.Votes.Where(v => v.Iddocument == document.Iddocument).ToListAsync();
            }
            HomeModel homeModel = new HomeModel
            {
                Documents = documents
            };
            homeModel.orderDocuments();


            return View(homeModel);
        }

        public async Task<IActionResult> Faculties()
        {
            if (_context.Faculties == null)
            {
                return NotFound();
            }
            List<Faculty> faculties = await _context.Faculties.Where(f => f.Idfaculty < 50).ToListAsync();
            return View(faculties);
        }

        public async Task<IActionResult> Faculty(int? id)
        {
            if (id == null || _context.Faculties == null)
            {
                return NotFound();
            }

            var faculty = await _context.Faculties.FirstOrDefaultAsync(f => f.Idfaculty == id);
            if (faculty == null)
            {
                return NotFound();
            }
            List<Field> fields = await _context.Fields.Where(f => f.Idfaculty == id).ToListAsync();
            for(int i=0; i<fields.Count(); i++) 
            {
                fields.ElementAt(i).Documents = await _context.Documents.Where(d => d.Idfield == fields.ElementAt(i).Idfield).ToListAsync();
                for(int j=0; j < fields.ElementAt(i).Documents.Count(); j++) 
                {
                    List<Vote> votes = await _context.Votes.Where(v => v.Iddocument == fields.ElementAt(i).Documents.ElementAt(j).Iddocument).ToListAsync();
                    fields.ElementAt(i).Documents.ElementAt(j).Votes = votes;
                }
                
                fields.ElementAt(i).Documents = await _context.Documents.Where(d => d.Idfield == fields.ElementAt(i).Idfield).ToListAsync();
            }
            faculty.Fields = fields;
            return View(faculty);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

UdeCDocsMVC/Views/Home/Faculties.cshtml
@model IEnumerable<UdeCDocsMVC.Models.Faculty>
@{
    ViewData["Title"] = "Facultades";
    Layout = "_Layout_Session";
}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.1/font/bootstrap-icons.css">

<div style="justify-content:center; align-content:center; margin-bottom:30px; margin-left:140px;align-items:center;">
    @foreach (var item in Model)
    {
        <div class="container-faculty">
            <div class="info-faculty">
                @if (@item.Idfaculty == 1)
                {
                    <a name="ingenieria" />
                    <img src="~/img/ingenieria.png"
                 style="float: right;
                 margin-right:0px;
                 margin-top:0px;
                 margin-left: 50px;
                 height:300px;">
                }
                else
                {
                    @if (@item.Idfaculty == 2)
                    {
                        <a name="educacion" />
                        <img src="~/img/educacion.png"
                 style="float: right;
                        margin-right: 7px;
                        margin-top: 60px;
                        margin-left: 50px;
                        height: 260px;
                        margin-bottom:55px;">
                    }
                    else
                    {
                        @if (@item.Idfaculty == 3)
                        {
                            <a name="salud" />
                            <img src="~/img/salud.png"
                 style="float: right;
                            margin-right: 10px;
                            margin-top: 30px;
                            margin-left: 50px;
                            height: 280px;
                            margin-bottom:0px;">
                        }
                        else
                        {
                        } @if (@item.Idfaculty == 4)
                        {
                            <a name="administración" />
                            <img src="~/img/administrar.png"
                 style="float: right;
                            margin-right: 10px;
                            margin-left: 50px;
                            height: 260px;
                            margin-bottom:0px;">
                        }
                        else
                        {
                            @if (@item.Idfaculty == 5)
                            {
                                <a name="agronomía" />
                                <img src="~/img/agro.png"
                 style="float: right;
                                margin-right: 10px;
                                margin-left: 50px;
                                height: 280px;
                                margin-bottom:0px;
                                margin-top:0px;">
                            }
                            else
                            {
                                @if (@item.Idfaculty == 6)
                                {
                                    <a name="deporte" />
                                    <img src="~/img/deporte.png"
                 style="float: right;
                                    margin-top: 0px;
                                    margin-left: 60px;
                                    margin-bottom: 0px;
                                    right:0px;
                                    height: 255px;">
                                }
                                else
                                {
                                    @if (@item.Idfaculty == 7)
                                    {
                                        <a name="humanidades" />
                                        <img src="~/img/humanidad.png"
                 style="float: right;
                                        margin-right: 20px;
                                        margin-top: 50px;
                                        margin-left: 50px;
                                        margin-bottom:0px;
                                        height: 310px;">
                                    }
                                }
                            }
                        }
                    }

                }
                @if (@item.Idfaculty == 4 || @item.Idfaculty == 5 || @item.Idfaculty == 6)
                {
                    <h2>@Html.DisplayFor(ModelItem=>item.Faculty1)</h2>
                    <p>@Html.DisplayFor(ModelItem=>item.Description)</p>
                    <a class="btn btn-outline-success" asp-controller="Home" asp-action="Faculty" asp-route-id="@item.Idfaculty">Ver documentos</a>
                    <br />
                }
                else
                {
                    <h2>@Html.DisplayFor(ModelItem=>item.Faculty1)</h2>
                    <p>@Html.DisplayFor(ModelItem=>item.Description)</p>
                    <i></i>
                    <a class="btn btn-outline-success" asp-controller="Home" asp-action="Faculty" asp-route-id="@item.Idfaculty">Ver documentos</a>
                }

            </div>
        </div>
        <br />

    }
</div>

UdeCDocsMVC/Views/Home/Faculty.cshtml
@model UdeCDocsMVC.Models.Faculty
@{
    <!--este es el titulo de la ventana-->
    ViewData["Title"] = "Facultad de " + Model.Faculty1;
    Layout = "_Layout_Session";
}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.1/font/bootstrap-icons.css">
<div>
    <!--acá se carga cada uno de las carreras de la facultdad-->
    @for (int i = 0; i < Model.Fields.Count(); i++)
    {
        <!--este if es para saber si la carrera tiene documentos, si no tienen no se muestra nada-->
        if (Model.Fields.ElementAt(i).Documents.Count() > 0)
        {
            <!--nombre de la carrera-->
            <h2 id="titleCareer">@Model.Fields.ElementAt(i).Field1</h2>
            if (Model.Fields.ElementAt(i).Field1 == "Facultad de Ingenieria")
            {
                <a name="ingenieria"></a>
            }
            <br />
            <!--esta tabla va a mostrar cada uno de los documentos que tiene la carrera-->
            <!--acá se cargan cada uno de los documentos de la carrera-->
            @foreach (var item in Model.Fields.ElementAt(i).Documents)
            {
                <div class="container-docFac">

                    <div class="info-docFac">
                        <img src="~/img/logo2.png">
                        <h2>@Html.DisplayFor(modelItem => item.Name)</h2>
                        <p id="abstract">@item.Abstract</p>
                        <p id=keywords>@Html.DisplayFor(modelItem => item.Keywords)</p>
                        <p id="authors">@Html.DisplayFor(modelItem => item.Authors)</p>

                        <i class="bi bi-hand-thumbs-up-fill" style="font-size:30px; color:#134410;margin-right:10px;"></i>
                        @item.Votes.Where(v => v.IdtypeVote == 1).Count()
                        <i class="bi bi-hand-thumbs-down-fill" style="font-size:30px; color:#134410;"></i>
                        @item.Votes.Where(v => v.IdtypeVote == 2).Count()
                        <br />
                        <br />
                        <a asp-controller="Documents" asp-action="Details" asp-route-id="@item.Iddocument" class="bi bi-eye-fill" style="font-size:30px; color:#134410;margin-right:10px;"></a>
                        <a asp-controller="DocumentsAPI" asp-action="GetDocument" asp-route-id="@item.Iddocument" class="bi bi-filetype-json" style="font-size:30px; color:#134410;"></a>
                        <p style="color:dimgrey; text-align:right;">@Html.DisplayFor(modelItem => item.PublicationDate)</p>
                    </div>
                </div>


            }

            <br />
        }
    }
</div>

UdeCDocsMVC/Views/Home/Index.cshtml
@model UdeCDocsMVC.Models.SysModels.HomeModel
@{
    ViewData["Title"] = "Home Page";
    Layout = "_Layout_Session";
}
@section headerSection{
    <header class="py-5 bg-image-full" style="background-image: linear-gradient(rgba(0, 0, 0, 0.5),rgba(0, 0, 0, 0.5)),url('https://images.unsplash.com/photo-1619410283995-43d9134e7656?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80')">
        <div class="text-center my-5">
            <img class="img-fluid rounded-circle mb-4" src="https://images.unsplash.com/photo-1600003263720-95b45a4035d5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80" alt="..." />
            <h1 class="text-white fs-3 fw-bolder">Facultad de Ingeniería</h1>
            <a class="text-white-50 mb-0" asp-controller="Home" asp-action="Faculty" asp-route-id="1">Descubre</a>
        </div>
    </header>
}


    @for (int i = 0; i < Model.DocumentsOrder.Count; i++)
    {
        if (i < 10)
        {
        <br />
        <div class="card" style="box-shadow: 0px 0px 30px black;">
                <h4 class="card-header">@Model.DocumentsOrder.ElementAt(i).Name</h4>
                <div class="card-body">
                    <h5 class="card-title">@Model.DocumentsOrder.ElementAt(i).Keywords</h5>
                    <h6 class="card-title">@Model.DocumentsOrder.ElementAt(i).PublicationDate</h6>
                    <p class="card-text">@Model.DocumentsOrder.ElementAt(i).Abstract</p>
                    <a class="btn btn-success" asp-controller="DocumentsAPI" asp-action="GetDocument" asp-route-id="@Model.DocumentsOrder.ElementAt(i).Iddocument">JSON</a>
                    <a class="btn btn-primary" asp-controller="Documents" asp-action="Details" asp-route-id="@Model.DocumentsOrder.ElementAt(i).Iddocument">Ver documento</a>
                </div>
            </div>
        }
        <br />

    }
<br />
<br />
<br />